apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "appmesh-grafana.fullname" . }}-datasources
  labels:
{{ include "appmesh-grafana.labels" . | indent 4 }}
data:
  datasources.yaml: |-
    apiVersion: 1
    deleteDatasources:
      - name: prometheus
    datasources:
    - name: prometheus
      type: prometheus
      access: proxy
      url: {{ .Values.url }}
      isDefault: true
      editable: true
      version: 1
