apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "appmesh-grafana.fullname" . }}-providers
  labels:
{{ include "appmesh-grafana.labels" . | indent 4 }}
data:
  providers.yaml: |+
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /etc/grafana/dashboards
